title: "סטטיסטיקה לפסיכולוגיה א'"
description: "סיכום קורס סטטיסטיקה לפסיכולוגיה - אוניברסיטת תל אביב"
author: "Orin Levi"
baseurl: "/Statistics_1_sum"
url: "https://orinlevi.github.io"

markdown: kramdown

include:
  - units

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - "*.tex"
  - "*.aux"
  - "*.log"
  - "*.pdf"
  - "*.synctex.gz"
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - "_posts"
  - "vendor"
  - "vendor/bundle"
